# Generated by Django 2.2.4 on 2019-11-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TB_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_code', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('dep', models.CharField(max_length=32)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_VsSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TB_Skill')),
                ('worker_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TB_Worker')),
            ],
        ),
    ]
